---
provisioner:
  name: shell
  data_path: .

driver:
  name: docker_cli

verifier:
  ruby_bindir: /usr/bin

transport:
  name: docker_cli

platforms:
- name: ubuntu
  driver_config:
    run_command:
    - apt update && apt install -y sudo curl ruby unzip

suites:
- name: oneagent-default
- name: oneagent-32
- name: oneagent-64
- name: oneagent-64-java
- name: oneagent-64-nginx
- name: oneagent-64-nodejs