---
provisioner:
  name: shell
  data_path: .

driver:
  name: docker_cli

verifier:
  ruby_bindir: /usr/bin

transport:
  name: docker_cli

platforms:
- name: ubuntu
  driver_config:
    image: ubuntu:16.04
    run_command:
    - apt update && apt install -y sudo ruby curl unzip

suites:
- name: oneagent-default
- name: oneagent-32
- name: oneagent-64
- name: oneagent-64-apache
  driver_config:
    image: webdevops/apache:ubuntu-16.04
- name: oneagent-64-java
- name: oneagent-64-nginx
- name: oneagent-64-nodejs