---
provisioner:
  name: shell
  data_path: .

driver:
  name: docker_cli

verifier:
  ruby_bindir: /usr/bin

transport:
  name: docker_cli

platforms:
- name: alpine
  driver_config:
    run_command:
    - apk add --no-cache sudo ruby ruby-io-console openssl bash

suites:
- name: oneagent-default
- name: oneagent-32
- name: oneagent-64